### ISSUE TITLE
Version Tag Check - Implement PoC

### ISSUE THREAD

**Issue by miroslavpojer** [AbsaOSS/version-tag-check#1]
Implement PoC

```[tasklist]
### Tasks
- [ ] https://github.com/AbsaOSS/version-tag-check/issues/2
- [ ] https://github.com/AbsaOSS/version-tag-check/issues/3
- [ ] https://github.com/AbsaOSS/version-tag-check/issues/4
```

**Comment by miroslavpojer** [comment]
Goal reached. Closing Epic.
